---
title: "Final Project - Visit Scotland"
output:
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(here)
library(janitor)
```

```{r}
activities_clean <- read_csv(here("clean_data/clean_activities.csv"))
clean_location   <- read_csv(here("clean_data/clean_location.csv"))
activities_clean %>% 
  distinct(year) %>% 
  arrange(year)
```


# Q1. What kind of tourism activity generates the highest income for Scotland?
```{r}
highest_income <- activities_clean %>% 
   filter(breakdown_of_domestic_tourism == "Expenditure", tourism_activity != "All") %>% 
  group_by(tourism_activity) %>% 
  summarise(expenditure_per_million_pounds  = sum(value))


highest_income %>% 
   slice_max(expenditure_per_million_pounds)


```
 
 
```{r}
my_themes <-  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_line(colour = "#A7C5CD"),
        panel.background = element_rect(fill = "#a0a3a0"),
        plot.background = element_rect(fill = "#a0a3a0"),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

```{r, fig.width= 10}
highest_income %>% 
   ggplot(aes(y = reorder(tourism_activity, -expenditure_per_million_pounds), x = expenditure_per_million_pounds)) +
  geom_bar(stat = "identity") +
    labs(
       title = "the highest income for Scotland tourism from 2013 to 2019",
          x = " per million pounds",
          y = "tourism activity"
  ) +
  my_themes 
```
 
 # Q2. Which kind of activity generates the most visits to sites?

```{r}
most_visits <- activities_clean %>% 
   filter(breakdown_of_domestic_tourism == "Visits", tourism_activity != "All") %>% 
  group_by(tourism_activity) %>% 
  summarise(activity_per_million_visits  = sum(value))

most_visits %>% 
   slice_max(activity_per_million_visits)
```

```{r, fig.width= 10}
most_visits %>% 
   ggplot(aes(y = reorder(tourism_activity, -activity_per_million_visits), x = activity_per_million_visits)) +
  geom_bar(stat = "identity") +
    labs(
      title = "most visits to sites tourism from 2013 to 2019",
    y = "tourism activity",
    x = " per million visits"
  ) +
   my_themes 
```

# Q4
## What type of locations receive the most visits?
```{r}
most_visit_loca <- clean_location %>% 
  filter(breakdown_of_domestic_tourism == "Visits", type_of_location_visited != "All areas") %>% 
  group_by(type_of_location_visited) %>% 
  summarise(most_visits_location = sum(value))

most_visit_loca %>% 
  slice_max(most_visits_location)
```


```{r, fig.width= 10}
most_visit_loca %>% 
   ggplot(aes(y = reorder(type_of_location_visited, -most_visits_location), x = most_visits_location)) +
  geom_bar(stat = "identity") +
    labs(
       title = "locations receive the most visits from 2013 to 2019",
          x = " per million visits",
          y = "tourism activity"
  ) +
   my_themes
```

## What kinds of locations do people spend the most in?

```{r}
most_spend_loca <- clean_location %>% 
  filter(breakdown_of_domestic_tourism == "Expenditure", type_of_location_visited != "All areas") %>% 
  group_by(type_of_location_visited) %>% 
  summarise(most_spend_location = sum(value))

most_spend_loca %>% 
  slice_max(most_spend_location)
```

```{r, fig.width= 10}
most_spend_loca %>% 
   ggplot(aes(y = reorder(type_of_location_visited, -most_spend_location), x = most_spend_location)) +
  geom_bar(stat = "identity") +
    labs(
       title = "locations do people spend the most in between 2013 to 2019",
          x = " per million pounds",
          y = "tourism activity"
  ) +
   my_themes 
```

```{r}
clean_location %>% 
  filter(breakdown_of_domestic_tourism == "Expenditure", type_of_location_visited != "All areas") %>% 
  group_by(year) %>% 
  summarise(most_spend = sum(value)) %>% 
  ggplot(aes(x = year, y = most_spend)) +
  geom_point() +
   geom_line() +
      labs(
       title = "most spend from 2013 to 2019",
          x = "Year",
          y = "Expenditure"
  ) +
  my_themes  
```

