---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

 
```{r}
library(tidyverse)
library(here)
library(janitor)
```
 
 
 
```{r}
regional_domestic <- read_csv(here("data/regional_domestic_tourism.csv"))
accomodation <- read_csv(here("data/scottish_accomodation_occupancy.csv"))
activities <- read_csv(here("data/tourism_day_visits_activities.csv"))
transport <- read_csv(here("data/tourism_day_visits_transport.csv"))
location <- read_csv(here("data/tourism_day_visits_location.csv"))
demographics <- read_csv(here("data/tourism_day_visits_demographics.csv"))
```
 
# cleaning activities dataset
## check if any NA
```{r}
activities %>% 
   summarise(across(.cols = everything(),
                   .fns = ~sum(is.na(.x))))
```
 
## clean names and delete feature code and measurement columns, rename data_code to year 
```{r}
clean_activities <- activities %>% 
  clean_names() %>% 
  rename(year = date_code ) %>% 
  select(-feature_code, -measurement)

clean_activities
```
 
# cleaning location dataset
## check if any NA.
```{r}
location %>% 
   summarise(across(.cols = everything(),
                   .fns = ~sum(is.na(.x))))
```

## clean names and delete feature code and measurement columns, rename data_code to year.

```{r}
clean_location <- location %>% 
  clean_names() %>% 
  rename(year = date_code ) %>% 
  select(-feature_code, -measurement)

  clean_location  
```
  
## cleaning transport dataset.
```{r}
clean_transport <- transport %>% 
  clean_names() %>% 
  rename(year = date_code ) %>% 
  select(-feature_code, -measurement)

clean_transport
```
 
# writing clean dataset to clean data folder 
```{r}
write_csv(clean_activities, here("clean_data/clean_activities.csv"))
write_csv(clean_location, here("clean_data/clean_location.csv"))
write_csv(clean_transport, here("clean_data/clean_transport.csv"))
```

 
 